version: '3.8'

services:
  api-gateway: 
    image: codebd/api-gateway:v0.01
    ports:
      - '5000:3000'
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
      - '8001:8001'
