name: Build API Gateway Docker Image and Push

on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Docker Build
      run: |
        apt update -y
        apt install make docker.io -y