name: Build API Gateway Docker Image and Push

on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Docker Build
        run: |
          cd api-gateway
          make build
          # docker build -t api-gateway:v1.0.0 .
